name: test gh actions
on: pull_request
env:
    PR_NUMBER: ${{ github.event.number}}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_ACTOR: ${{ github.actor }}
    GITHUB_WORKFLOW: ${{ github.workflow }}
    GITHUB_HEAD_REF: ${{ github.head_ref }}
    GITHUB_BASE_REF: ${{ github.base_ref }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}
    GITHUB_REF: ${{ github.ref }}
    GITHUB_SHA: ${{ github.sha }}
    GITHUB_WORKSPACE: ${{ github.workspace }}
    GITHUB_ACTION: ${{ github.action }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}

jobs:
    Testjob:
        runs-on: ubuntu-latest

        steps:
            - name: check out source files
              uses: actions/checkout@v3

            - name: Get codeowners
              id: codeowners
              uses: SvanBoxel/codeowners-action@v1
              with: 
                path: '.github/CODEOWNERS'
            - run: |
                echo ${{ steps.codeowners.outputs.codeowners }};

            - name: Get changed files
              id: changed-files
              uses: tj-actions/changed-files@v38
        
            - name: List all changed files
              run: |
                echo ${{ steps.codeowners.outputs.codeowners }};
                for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                  echo "current file: $file"
                  if ${{ steps.codeowners.outputs.codeowners }} | grep "$file"; then
                    echo "$file is owned by a codeowner"
                  else
                    echo "$file is not owned by a codeowner"
                  fi
                  echo "$file was changed"
                done
