name: test gh actions
on: [pull_request]
env:
    PR_NUMBER: ${{ github.event.number}}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    GITHUB_REPOSITORY: ${{ github.repository }}
    GITHUB_ACTOR: ${{ github.actor }}
    GITHUB_WORKFLOW: ${{ github.workflow }}
    GITHUB_HEAD_REF: ${{ github.head_ref }}
    GITHUB_BASE_REF: ${{ github.base_ref }}
    GITHUB_EVENT_NAME: ${{ github.event_name }}
    GITHUB_REF: ${{ github.ref }}
    GITHUB_SHA: ${{ github.sha }}
    GITHUB_WORKSPACE: ${{ github.workspace }}
    GITHUB_ACTION: ${{ github.action }}
    GITHUB_EVENT_PATH: ${{ github.event_path }}

jobs:
    Testjob:
        runs-on: ubuntu-latest
        steps:
        - run: "echo PR_NUMBER: $PR_NUMBER"
        - run: "echo GITHUB_TOKEN: $GITHUB_TOKEN"
        - run: "echo GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
        - run: "echo GITHUB_ACTOR: $GITHUB_ACTOR"
        - run: "echo GITHUB_WORKFLOW: $GITHUB_WORKFLOW"
        - run: "echo GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
        - run: "echo GITHUB_BASE_REF: $GITHUB_BASE_REF"
        - run: "echo GITHUB_EVENT_NAME: $GITHUB_EVENT_NAME"
        - run: "echo GITHUB_REF: $GITHUB_REF"
        - run: "echo GITHUB_SHA: $GITHUB_SHA"
        - run: "echo GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
        - run: "echo GITHUB_ACTION: $GITHUB_ACTION"
        - run: "echo GITHUB_EVENT_PATH: $GITHUB_EVENT_PATH"
